config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :companies, only: [:new, :create, :show] do
    member do 
      get 'fabrics' 
    end    
  end

  resources :fabrics, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :company_user, only: [:create, :new, :update] 

  get 'cart', to: 'fabric_to_carts#show_user_cart'
  delete 'cart', to: 'fabric_to_carts#destroy_all'
  
  get 'my_company', to: 'companies#show'
  get 'search_company', to: 'companies#search'
  resources :fabric_to_carts, only: [:destroy, :update, :create]
  post 'set_delivery_point', to: 'fabric_to_carts#set_delivery_point'

  resources :delivery_points, only: [:create, :destroy, :index] do
  	member do
			get :as_favourite  		
  	end 
  end

  resources :orders, only: [:new, :index] do
    collection do
      get 'pending'
    end
  end

  resources :payments, only: :new do
    collection do
      get 'empty_cart'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :labels, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fabric_to_cart.rb
class FabricToCart < ApplicationRecord
  belongs_to :fabric
  has_one :company, through: :fabric
  belongs_to :user
  belongs_to :delivery_point, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  validate :min_quantity?, :if => :condition_testing?

  def self.total_price(fabric_to_carts)
  	sum = 0
  	fabric_to_carts.each do |fabric_to_cart|
  		sum += fabric_to_cart.quantity * fabric_to_cart.fabric.price unless fabric_to_cart.is_sample
  	end
  	return sum
  end

  def self.total_sample_price(user)
    sum = 0
    fabric_to_carts = FabricToCart.where(user: user).where(is_sample: true)
    fabric_to_carts.each do |fabric_to_cart|
      sum += fabric_to_cart.quantity * fabric_to_cart.fabric.sample_price
    end
    return sum
  end

  def price
  	quantity * self.fabric.price
  end

  def sample_price
  	self.fabric.sample_price
  end

  def self.cart_by_supplier(cart)
    cart_by_supplier = {}
    cart.each do |order_item|
      if cart_by_supplier[order_item.company].nil?
        cart_by_supplier[order_item.company] = [order_item]
      else
        cart_by_supplier[order_item.company] << order_item
      end
    end
    return cart_by_supplier
  end

  def self.samples(cart)
    samples = []
    cart.each do |x|
      if x.is_sample
        samples << x
      end
    end
  return samples
  end

  private

  def min_quantity?
    if quantity
      if quantity < fabric.minimum_qty
        errors.add(:quantity, "A quantidade mínima para esse item é de #{fabric.minimum_qty}")
      end
    end
  end

  def condition_testing?
    !is_sample
  end
  
end

app/controllers/fabric_to_carts_controller.rb
class FabricToCartsController < ApplicationController
	before_action :set_fabric_to_cart, only: [:destroy, :update]

	def show_user_cart
		cart = policy_scope(FabricToCart).order(:created_at)
		@cart = FabricToCart.cart_by_supplier(cart)
		@samples = FabricToCart.samples(cart)
	end

	def create
		@fabric = Fabric.find(params[:fabric_to_cart][:fabric_id])
		if (params[:fabric_to_cart][:is_sample])
			@fabric_to_cart = FabricToCart.new(quantity: 1, is_sample: true)
		else
		@fabric_to_cart = FabricToCart.new(cart_params)
		end
		authorize @fabric_to_cart
		@fabric_to_cart.user = current_user
        @fabric_to_cart.fabric = @fabric

    	current_user.update(checkout_session_id: nil)

	    if @fabric_to_cart.save
				if params[:commit] == "COMPRAR AGORA"
					redirect_to cart_path
				else
					redirect_to fabrics_path, notice: 'Produto adicionado ao carrinho!'
				end
		else
			render "fabrics/show"
		end
	end
	
	def destroy
		authorize @cart
		@cart.destroy
		redirect_to cart_path
	end

	def destroy_all
		cart = policy_scope(FabricToCart)
		cart.each do |item|
			authorize item
			item.destroy
		end
		redirect_to cart_path
	end

	def update
		authorize @cart
		if @cart.update(cart_params)
			current_user.update(checkout_session_id: nil)
			redirect_to cart_path
		else
			render :show_user_cart
		end
	end

	def set_delivery_point
		f_carts = FabricToCart.where(user: current_user)
		
		unless params[:delivery_point][:id] == ""

			delivery_point = DeliveryPoint.find(params[:delivery_point][:id])
			
			f_carts.each do |f_cart|
				authorize f_cart
				f_cart.update(delivery_point: delivery_point)
			end

			redirect_to new_payment_path
		else
			if current_user.delivery_points.nil?
				@error_message = "Você precisa criar um endereço"
			else
				@error_message = "Você precisa selecionar um endereço"
			end
			@delivery_point = DeliveryPoint.new
			@delivery_points = policy_scope(DeliveryPoint).order('created_at DESC')
			render "delivery_points/index"
		end
	end

	private

	def cart_params
		params.require(:fabric_to_cart).permit(:quantity)
	end

	def set_fabric_to_cart
		@cart = FabricToCart.find(params[:id])
	end

end

app/views/fabric_to_carts/_company_card.html.erb
<div class="wrapp-supplier">
    <div class="d-flex justify-content-between align-items-center header">
        <div class="d-flex align-items-center">

            <% if company.logo.attached? %>
            <!-- mudar para empresa -->
            <%= cl_image_tag company.logo.key, alt: "#{company.name} logo", class: "mr-1" , height: 60, width: 60, crop: :fill%>
            <% else %>
            <i class="fas fa-building"></i>
            <% end %>
            <h2 class="mx-2"><%= company.name %></h2>
        </div>
        <p><%= number_to_currency(
				FabricToCart.total_price(cart[company]).fdiv(100),
				unit: 'R$',
				separator: ",",
				delimiter: ".",
				format: "%u %n"
				)
			%>
        </p>
    </div>

    <hr>



    <% cart[company].each do |fabric_to_cart| %>
    <% unless fabric_to_cart.is_sample %>
    <div class="row justify-content-end">
        <div class="col-11">
            <div class="card-product">
                <% if fabric_to_cart.fabric.photos.attached? %>
                <%= cl_image_tag fabric_to_cart.fabric.photos[0].key, alt: "textile picture" %>
                <% else %>
                <%= image_tag "textile_roll", alt: "undefined textile" %>
                <% end %>
                <div class="card-product-infos">
                    <div>
                        <h3><%= fabric_to_cart.fabric.name %></h3>
                        <p>Qtd: <%= fabric_to_cart.quantity %>m</p>
                        <% unless fabric_to_cart.delivery_point.nil? %>
                        <p>Entregar para: <%= fabric_to_cart.delivery_point.name %></p>
                        <% end %>
                    </div>
                    <div class="card-options">
                        <p>
                            <%= number_to_currency(
										fabric_to_cart.price.fdiv(100),
										unit: 'R$',
										separator: ",",
										delimiter: ".",
										format: "%u %n"
									) 
								%>
                        </p>

                        <div class="d-flex align-items-center justify-content-end my-1">
                            <%= form_for fabric_to_cart, remote: true do |f| %>
                            <%= f.hidden_field :quantity, value: (fabric_to_cart.quantity - 5) %>
                            <%= f.submit "-", class: (fabric_to_cart.quantity >= fabric_to_cart.fabric.minimum_qty + 5)? "btn-add mr-1" : "btn-add mr-1 disabled"  %>
                            <% end %>
                            <%= form_for fabric_to_cart, remote: true do |f| %>
                            <%= f.hidden_field :quantity, value: (fabric_to_cart.quantity + 5) %>
                            <%= f.submit "+", class: "btn-add" %>
                            <% end %>
                        </div>

                        <%= link_to fabric_to_cart, method: :delete, data: {confirm: "Deseja apagar esse item?"} do  %>
                        <i class="fas fa-trash mx-2"></i>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
    <% end %>
</div>

app/views/fabric_to_carts/_samples.html.erb
<div class="wrapp-supplier">
    <div class="d-flex justify-content-between align-items-center header">
        <h2 class="amostras-title">Amostras</h3>
        <p><%= number_to_currency(
                FabricToCart.total_sample_price(current_user).fdiv(100),
                unit: 'R$',
                separator: ",",
                delimiter: ".",
                format: "%u %n")
            %>
        </p>
    </div>
    <hr>
    <% @samples.each do |sample| %>
        <div class="row justify-content-end">
            <div class="col-11">
                <div class="card-product">
                    <% if sample.fabric.photos.attached? %>
                        <%= cl_image_tag sample.fabric.photos[0].key, alt: "textile picture" %>
                    <% else %>
                        <%= image_tag "textile_roll", alt: "undefined textile" %>
                    <% end %>
                    <div class="card-product-infos">
                        <div>
                            <h3><%= sample.fabric.name %></h3>
                            <p><%= sample.fabric.company.name %></p>
                        </div>
                        <div class="card-options">
                            <p><%= number_to_currency(
                                    sample.sample_price.fdiv(100),
                                    unit: 'R$',
                                    separator: ",",
                                    delimiter: ".",
                                    format: "%u %n") %>
                            </p>

                            <%= link_to sample, method: :delete, data: {confirm: "Deseja apagar esse item?"} do  %>
                                <i class="fas fa-trash mx-2"></i>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

app/views/fabric_to_carts/show_user_cart.html.erb
<div class="container my-4">
    <div class="d-flex justify-content-between align-items-center">
        <h1>Meu Carrinho</h1>
        <% unless @cart.empty? %>
            <%= link_to cart_path, method: :delete, data: {confirm: "Você deseja retirar todos os itens do seu carrinho?"}, title:  "Esvaziar carrinho"  do %>
                <i class="fas fa-trash" style="color: red;"></i>
            <% end %>
        <% end %>
    </div>

    <% if @cart.empty? %>
        <p>Você não adicionou nenhum elemento ao seu carrinho</p>
        <%= link_to fabrics_path do %>
            <button class="btn btn-success">Descubra nossos tecidos</button>
        <% end %>
    <% else %>

    <% unless @samples.empty? %>
        <%= render partial: 'samples', locals: { cart: @samples} %>    
    <% end %>
    

    <% @cart.keys.each do |company| %>
        <%unless @cart[company].all? {|x| x.is_sample}%>
            <%= render partial: 'company_card', locals: {company: company, cart: @cart} %>
        <% end %>
    <% end %>
    <div class="d-flex justify-content-end">
        <%= link_to "Validar Carrinho", delivery_points_path, class: "btn btn-success"  %>
    </div>
    <% end %>

</div>