config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :companies, only: [:new, :create, :show] do
    member do 
      get 'fabrics' 
    end    
  end

  resources :fabrics, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :company_user, only: [:create, :new, :update] 

  get 'cart', to: 'fabric_to_carts#show_user_cart'
  delete 'cart', to: 'fabric_to_carts#destroy_all'
  
  get 'my_company', to: 'companies#show'
  get 'search_company', to: 'companies#search'
  resources :fabric_to_carts, only: [:destroy, :update, :create]
  post 'set_delivery_point', to: 'fabric_to_carts#set_delivery_point'

  resources :delivery_points, only: [:create, :destroy, :index] do
  	member do
			get :as_favourite  		
  	end 
  end

  resources :orders, only: [:new, :index] do
    collection do
      get 'pending'
    end
  end

  resources :payments, only: :new do
    collection do
      get 'empty_cart'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :labels, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/delivery_point.rb
class DeliveryPoint < ApplicationRecord
  belongs_to :user
  has_many :fabric_to_carts, dependent: :nullify
  has_many :orders, dependent: :nullify

  def to_s
  	[name, rua, numero, bairro, cep, cidade, uf, "comment: #{comment}", "contact: #{contact}"].join(";")
  end
end

app/controllers/delivery_points_controller.rb
class DeliveryPointsController < ApplicationController
	before_action :find_delivery_point, only: [:destroy, :as_favourite]
	
	def index 
		@delivery_point = DeliveryPoint.new
		@delivery_points = policy_scope(DeliveryPoint).order('created_at DESC')
	end

	def create
		delivery_point = DeliveryPoint.new(params_delivery_point)
		delivery_point.user = current_user
		authorize delivery_point

		if delivery_point.save
			redirect_to delivery_points_path
		else
			render :index
		end
	end

	def destroy
		authorize @delivery_point
		@delivery_point.destroy
		redirect_to cart_path
	end

	def as_favourite
		user_delivery_points = DeliveryPoint.where(user: current_user)
		
		user_delivery_points.each do |d_point|
			if d_point != @delivery_point && d_point.favourite?
				d_point.update(favourite: false)
			end
		end
		
		@delivery_point.update(favourite: true)
		redirect_to delivery_points_path
	end

	private

	def params_delivery_point
		params.require(:delivery_point).permit(:name, :uf,:rua, :cidade, :bairro, :numero, :complemento, :cep, :contact, :comment)
	end

	def find_delivery_point
		@delivery_point = DeliveryPoint.find(params[:id])
		authorize @delivery_point
	end
end

app/views/delivery_points/_delivery_point_form.html.erb
<%= simple_form_for delivery_point, remote: true do |f| %>
<div class="form-item">
    <%= f.input :name,label: "Nome" %>
</div>
<div class="d-flex d-flex justify-content-center">
    <div class="form-item row-with-3">
        <%= f.input :cep, :input_html => {:id => "cep"} %>
    </div>
    <div class="form-item row-with-3">
        <%= f.input :uf, :input_html => {:id => "uf"} %>
    </div>
    <div class="form-item row-with-3">
        <%= f.input :cidade, :input_html => {:id => "cidade"} %>
    </div>
</div>
<div class="d-flex d-flex justify-content-center">
</div>
<div class="d-flex d-flex justify-content-center">
    <div class="form-item row-with-2">
        <%= f.input :bairro, :input_html => {:id => "bairro"} %>
    </div>
    <div class="form-item row-with-2">
        <%= f.input :rua, :input_html => {:id => "rua"} %>
    </div>
</div>
<div class="d-flex d-flex justify-content-center">
    <div class="form-item row-with-2">
        <%= f.input :numero, :input_html => {:id => "numero"} %>
    </div>
    <div class="form-item row-with-2">
        <%= f.input :complemento, :input_html => {:id => "complemento"} %>
    </div>
</div>
<div class="form-item">
    <%= f.input :contact,label: "Contato" %>
</div>
<div class="form-item">
    <%= f.input :comment,label: "Comentário" %>
</div>
<div class="d-flex d-flex justify-content-center">
    <%= f.submit "Criar endereço", class: "btn btn-success" %>
</div>
<% end %>

app/views/delivery_points/_delivery_points_grid.html.erb
<div class="grid-delivery">
	
	<% @default_delivery_point = nil %>
	
	<% @delivery_points.each do |delivery_point| %>
		
		<% if delivery_point.favourite %>
			<div class="card-address selected" data-delivery=<%= delivery_point.id %>>
			<% @default_delivery_point = delivery_point.id %>
		<% else %>
			<div class="card-address" data-delivery=<%= delivery_point.id %>>
		<% end %>

			<h3><%= delivery_point.name %></h3>
			<div class="card-details">
				<p>Endereço: <%= delivery_point.cidade %> - <%= delivery_point.uf %>, <%= delivery_point.bairro %>, <%= delivery_point.rua %>, <%= delivery_point.numero %>, <%= delivery_point.complemento %></p>
				<p>CEP: <%= delivery_point.cep %></p>
				<p>Contato: <%= delivery_point.contact %></p>
				<p>Comentário: <%= delivery_point.comment %></p>
			</div>
			<div class="card-links">
				<%= link_to as_favourite_delivery_point_path(delivery_point) do %>
					<% if delivery_point.favourite %>
						<i class="fas fa-heart"></i>
					<% else %>
						<i class="far fa-heart"></i>
					<% end %>	
				<% end %>
				<%= link_to delivery_point, method: :delete, data: {confirm: "Deseja deletar esse endereço?"} do %>
					<i class="fas fa-trash"></i>
				<% end %>

			</div>
		</div>
	<% end %>
</div>

app/views/delivery_points/index.html.erb
<div class="container" id="delivery-part">
		
	<% if !@delivery_points.empty? %>
		<div class="d-flex align-items-center">
			<h2>Escolhe o endereço de entrega ou</h2>
			<button class="btn btn-secondary mx-4 delivery-point-form">crie um novo endereço</button>
		</div>

		<div class="hidden" id="delivery-point-form">
			<%= render partial: "delivery_points/delivery_point_form", locals: {delivery_point: @delivery_point} %>
		</div>
		
		<%= render partial: "delivery_points/delivery_points_grid" %>
	
		<div class="d-flex mb-4">
			<%= simple_form_for :delivery_point, url: {controller: :fabric_to_carts, action: :set_delivery_point} do |f| %>
				<%= f.hidden_field :id, id: "delivery-point-id", value: @default_delivery_point, require: true %>
				<% if @error_message %>
					<p class="alert alert-danger"><%= @error_message %></p>
				<% end %>
				<%= f.submit "Selecionar endereço", class: "btn btn-success", id: "select-delivery-point-button" %>
			<% end %>
		</div>

	<% else %>
		<h2>Indique o endereço de entrega</h2>
		<div id="delivery-point-form">
			<%= render partial: "delivery_points/delivery_point_form", locals: {delivery_point: @delivery_point} %>
		</div>
	<% end %>


	

</div>