config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :companies, only: [:new, :create, :show] do
    member do 
      get 'fabrics' 
    end    
  end

  resources :fabrics, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :company_user, only: [:create, :new, :update] 

  get 'cart', to: 'fabric_to_carts#show_user_cart'
  delete 'cart', to: 'fabric_to_carts#destroy_all'
  
  get 'my_company', to: 'companies#show'
  get 'search_company', to: 'companies#search'
  resources :fabric_to_carts, only: [:destroy, :update, :create]
  post 'set_delivery_point', to: 'fabric_to_carts#set_delivery_point'

  resources :delivery_points, only: [:create, :destroy, :index] do
  	member do
			get :as_favourite  		
  	end 
  end

  resources :orders, only: [:new, :index] do
    collection do
      get 'pending'
    end
  end

  resources :payments, only: :new do
    collection do
      get 'empty_cart'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :labels, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_base_fabric.html.erb
<div class="card card-fabric mx-2 p-1" id="fabric">
    <% unless fabric.photos[0].nil?%>
    <%= link_to fabric_path(fabric) do %>
    <%=  cl_image_tag fabric.photos[0].key, :transformation=>[{:width=>400, :height=>250, :crop=>"fill"}] %>
    <% end %>
    <% else %>
    <%= link_to fabric_path(fabric) do %>
    <%= image_tag "textile_roll.png", size: "250x250" %>
    <% end %>
    <% end %>

    <%= render './shared/edit_links', fabric: fabric %>

    <div class="card-body fabric">
        <div class="content">
            <div class="d-flex justify-content-between">
                <h5 class="card-title"><%= fabric.name %></h5>
                <p class="card-text"><strong>R$<%= fabric.price/100 %>/m</strong></p>
            </div>
            <p class="card-text"><%= fabric.composition %></p>
            <p class="hidden" id="searchable-item-color"><%= fabric.colour %></p>
            <p class="hidden" id="searchable-item-fabric-type"><%= fabric.fabric_type %></p>
            <p class="hidden" id="searchable-item-price"><%= fabric.price %></p>
            <%  unless fabric.labels.empty? %>
            <%  fabric.labels.each do |label| %>
            <p class="hidden" id="searchable-item-labels"><%= label.name %></p>
            <% end %>
            <div class="my-1 d-flex justify-content-center">
                <%= render './shared/labels_grid', fabric: fabric, size: 30 %>
            </div>
            <% end %>
        </div>
        <div>
            <div class="d-flex align-items-end  justify-content-between"> 
                <% if params[:id].nil?%>
                    <%= simple_form_for @fabric_to_cart, html: {class: "d-flex align-items-end"} do |f| %>
                            <%= f.input :fabric_id, :as => :hidden, :input_html => { :value => fabric.id } %>
                        <div class="d-flex align-items-end">
                            <%= f.input :quantity, label: false, :input_html => { :value => fabric.minimum_qty, style: "opacity: 0.5"}, :wrapper_html => {class: "form-index-fabric"}%>
                            <label style="opacity: 0.5">m</label>
                        </div>
                        <button type="submit" class="btn btn-success btn-card-index-cart" title="Adicionar ao Carrinho">
                            <i class="fas fa-cart-arrow-down"></i>
                        </button>

                    <% end %>
                    
                    <%= simple_form_for @fabric_to_cart, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
                        <%= f.input :fabric_id, :as => :hidden, :input_html => { :value => fabric.id } %>
                        <%= f.hidden_field :is_sample,  :value => true  %>

                        <button type="submit" class="btn btn-success btn-sm btn-card-index-sample" title="Pedir Amostra">
                            <i class="fas fa-swatchbook"></i>
                        </button>
                    <% end %>
                <% end %>

            </div>


        </div>
    </div>
</div>

app/views/shared/_company_banner.html.erb
<div class="company-background">
	<div class="container d-flex py-5">
		<% if company.logo.attached? %>
			<%= cl_image_tag company.logo.key, height: 150, width: 150, crop: :fill %>
		<% end %>
		<div class="ml-4 align-self-center">
			<h1><%= company.name %></h1>
			<p><%= company.description %></p>
		</div>
		
	</div>
</div>

app/views/shared/_edit_links.html.erb
	<% edit = (user_signed_in? && policy(fabric).edit?) %>
	<% destroy = user_signed_in? && policy(fabric).destroy? %>
	
	<% if edit || destroy %>	
			<div class="edit-links justify-content-center">
				<% if edit %>
	                <%= link_to edit_fabric_path(fabric) do %>
	                	<i class="fas fa-edit mr-2"></i>
	                <% end %>
	            <% end %>
	            
	            <% if destroy %>
	                <%= link_to fabric, method: :delete, data: {confirm: "Tem certeza que quer retirar esse produto da venda?"} do %>
	                	<i class="fas fa-trash ml-2"></i>
	                <% end %>
	            <% end %>
	        </div>
    <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_labels_grid.html.erb
<div class="labels-grid">
	<% fabric.label_to_fabrics.each do |label_to_fabric| %>
		<div class="label-show">
			<%= link_to labels_path do %>
				<%= cl_image_tag label_to_fabric.label.photo.key, height: size, crop: :scale %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon white fixed-top">
  <div>
    <%= link_to fabrics_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %> 
    <% end %>
    <%= link_to "Da Pluma à Pele", fabrics_path %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= current_user.name %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "user_green.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          
          <div class="dropdown-menu dropdown-menu-right dark-link" aria-labelledby="navbarDropdown">
            <% if current_user.company.nil? && current_user.owned_company.nil?  %>
              <%= link_to "Cadastre sua empresa", new_company_path, class: "dropdown-item"  %>
              <%= link_to "Junte-se a uma empresa", search_company_path, class: "dropdown-item"  %>
            <% end  %>
            <% unless current_user.owned_company.nil?  %>
              <%= link_to "Minha empresa", my_company_path(current_user.owned_company), class: "dropdown-item"  %>
            <% end  %>
            <%unless current_user.what_company.nil?%>
            <% if policy(current_user.what_company).fabrics?  %>
              <%= link_to "Meus produtos", fabrics_company_path(current_user.what_company), class: "dropdown-item"  %>
            <% end %>
            <% end %>
            <% unless current_user.orders.empty? %>
              <%= link_to "Meus pedidos", orders_path, class: "dropdown-item"  %>
            <% end %>
            <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item"  %>
            <%= link_to "Sair da conta", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Cadastre-se", new_user_registration_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            Login <%= image_tag "user_gray.png", class: "avatar" %>
          <% end %>
        </li>
      <% end %>
      <li>
        <%= link_to cart_path do  %>
          <i class="fa fa-shopping-cart ml-0" aria-hidden="true"></i>
          <span class='badge badge-warning' id='lblCartCount'><%= @quantity %></span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: fabrics_path, method: :get do |f| %>
  <div class="search-form-control form-group my-0">
    <%= f.input :query, 
    	class: "form-control string required",
    	remote: true,
    	label: false,  
    	input_html: {value: @query},
      placeholder: "Qual tecido você procura?"
    %>
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>