config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :companies, only: [:new, :create, :show] do
    member do 
      get 'fabrics' 
    end    
  end

  resources :fabrics, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  resources :company_user, only: [:create, :new, :update] 

  get 'cart', to: 'fabric_to_carts#show_user_cart'
  delete 'cart', to: 'fabric_to_carts#destroy_all'
  
  get 'my_company', to: 'companies#show'
  get 'search_company', to: 'companies#search'
  resources :fabric_to_carts, only: [:destroy, :update, :create]
  post 'set_delivery_point', to: 'fabric_to_carts#set_delivery_point'

  resources :delivery_points, only: [:create, :destroy, :index] do
  	member do
			get :as_favourite  		
  	end 
  end

  resources :orders, only: [:new, :index] do
    collection do
      get 'pending'
    end
  end

  resources :payments, only: :new do
    collection do
      get 'empty_cart'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :labels, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :fabrics, dependent: :destroy
	validates_format_of :cep, :with => /\A^\d{5}[-]?\d{3}$\Z/i
	validates_format_of :cnpj, :with => /[0-9]{2}\.?[0-9]{3}\.?[0-9]{3}\/?[0-9]{4}\-?[0-9]{2}/
	validates :name, presence: true
	has_one_attached :logo, dependent: :destroy
	belongs_to :owner, class_name: "User", foreign_key: "user_id"
	has_many :company_users, dependent: :destroy
	has_many :users, through: :company_users
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def new
        @company = Company.new
        authorize @company
    end

    def create
        @company = Company.new(company_params) 
        authorize @company
        @company.owner = current_user
        
        if @company.save
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @company = policy_scope(Company).find_by(owner: current_user)
        authorize @company
        @pending_users = CompanyUser.where(status: :pending).where("company_id = ?", @company.id)
        @active_users = CompanyUser.where(status: [:active]).where("company_id = ?", @company.id)
    end

    def search
        @companies = policy_scope(Company)
        authorize @companies
    
        if !params[:search].nil?
            @company = policy_scope(Company).find_by(cnpj: "#{params[:search][:query]}")
            if !@company.nil?
                authorize @company
            end
        end
    end

    def fabrics
        @company = Company.find(params[:id])
        authorize @company
        @fabrics = policy_scope(Fabric).where(company: @company)
    end

    private

    def company_params
        params.require(:company).permit(:name, :cep, :uf, :cidade, :bairro, :rua, :numero, :complemento, :cnpj, :description)
    end
        
end

app/views/companies/fabrics.html.erb
<%= render "./shared/company_banner", company: @company %>

<div class="container">
    <div class="row  my-5">
        <% if policy(Fabric).new? %>
        <%= link_to "Adicionar um novo produto", new_fabric_path, class: "btn btn-success btn-lg"  %>
        <% end %>
    </div>
    
    <% if @fabrics.empty? %>
        <h2>Sua empresa ainda não oferece produtos.</h2>
    <% else %>
        <h2>Os produtos oferecidos pela sua empresa:</h2>    
    <% end %>
    

    <div class="row">
        <div class="cards my-5 text-center">
            <% @fabrics.each do |fabric| %>
                <%= render "./shared/base_fabric", fabric: fabric %>
            <% end %>
        </div>
    </div>
</div>

app/views/companies/new.html.erb
<div class="container">
    <div class="m-4">
        <%= simple_form_for  @company do |f| %>
        <div class="d-flex d-flex justify-content-center">
            <div class="form-item row-with-2">
                <%= f.input :name,label: "Nome" %>
            </div>
            <div class="form-item row-with-2">
                <%= f.input :cnpj,label: "CNPJ" %>
            </div>
        </div>
        <div class="form-item">
            <%= f.input :description,label: "Descrição da empresa" %>
        </div>
        <div class="d-flex d-flex justify-content-center">
            <div class="form-item row-with-3">
                <%= f.input :cep, :input_html => {:id => "cep"} %> 
            </div>
            <div class="form-item row-with-3">
                <%= f.input :uf, :input_html => {:id => "uf"} %> 
            </div>
            <div class="form-item row-with-3">
                <%= f.input :cidade, :input_html => {:id => "cidade"} %> 
            </div>
        </div>
        <div class="d-flex d-flex justify-content-center">
        </div>
        <div class="d-flex d-flex justify-content-center">
            <div class="form-item row-with-2">
                <%= f.input :bairro, :input_html => {:id => "bairro"} %> 
            </div>
            <div class="form-item row-with-2">
                <%= f.input :rua, :input_html => {:id => "rua"} %> 
            </div>
        </div>
        <div class="d-flex d-flex justify-content-center">
            <div class="form-item row-with-2">
                <%= f.input :numero, :input_html => {:id => "numero"} %> 
            </div>
            <div class="form-item row-with-2">
                <%= f.input :complemento, :input_html => {:id => "complemento"} %> 
            </div>
        </div>


        <div class="d-flex d-flex justify-content-center">
            <%= f.submit "Criar empresa", class: "btn btn-outline-primary my-auto" %>
            <% end %>
        </div>
    </div>

app/views/companies/search.html.erb
<div class="container">


    <%= simple_form_for :search, url: search_company_path, method: :get do |f| %>
        <div class="search-form-control form-group">
            <%= f.input :query, 
            	class: "form-control string required",
            	remote: true,
                label: false,
                placeholder: "CNPJ da empresa",
            	input_html: {value: @query}
            %>
            <button name="button" type="submit" class="btn btn-flat">
                <i class="fas fa-search"></i> Search
            </button>
    </div>
    <% end %>

    <div class="d-flex justify-content-around">
        <% if @company.nil? && params[:search].nil? %>
        <% elsif @company.nil? && !params[:search].nil? %>
            <p>Company not found </p>
        <% else %>
            <p><%= @company.name %></p>

            <%= simple_form_for :company_user,url: company_user_index_path, method: :post do |f| %>
            <%= f.hidden_field :company_id, :value => @company.id %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :role, :value => :standard %>
            <%= f.hidden_field :status, :value => :pending %>
            <%= f.submit "Juntar-se a empresa", class: "btn btn-sm btn-success" %>
            <% end %>

        <% end  %>

    </div>

</div>

app/views/companies/show.erb
<%= render "./shared/company_banner", company: @company %>

<div class="container">
    <div class="employees">
        <% unless @pending_users.empty? %>
            <h2>Solicitações de cadastro na sua empresa</h2>
            <hr>

            <% @pending_users.each do |pending_user|%>            
            <div class="d-flex justify-content-between m-1">
                <%= pending_user.user.name %> : <%= pending_user.user.email %>
                <div class="d-flex align-items-center">
                    <%= simple_form_for :company_user,url: company_user_path(pending_user), method: :patch do |f| %>
                        <%= f.hidden_field :id, :value => pending_user.id %>        
                        <%= f.hidden_field :company_id, :value => @company.id %>
                        <%= f.hidden_field :user_id, :value => pending_user.user.id %>
                        <%=  f.hidden_field :role, :value => :standard %>
                        <%= f.hidden_field :status, :value => :active %>
                        <%= f.submit " Aceitar ", class: "btn btn-sm btn-success" %>
                    <% end  %>
                    <%= simple_form_for :company_user,url: company_user_path(pending_user), method: :patch do |f| %>
                        <%= f.hidden_field :id, :value => pending_user.id %>        
                        <%= f.hidden_field :company_id, :value => @company.id %>
                        <%= f.hidden_field :user_id, :value => pending_user.user.id %>
                        <%=  f.hidden_field :role, :value => :standard %>
                        <%= f.hidden_field :status, :value => :inactive %>
                        <%= f.submit " Recusar ", class: "btn btn-sm btn-danger ml-2", data: { confirm: "Tem certeza que deseja recusar esse funcionário? Essa ação não poderá ser cancelada." } %>
                    <% end  %>
                </div>
            </div>
            <% end %>
        <% end %>
    </div>
    <div class="employees my-5">
        <% if @company_users.nil? && @pending_users.empty? %>
            <h2>Você não tem funcionários cadastros na plataforma</h2>
            <hr>
        <% else %>  
          <h2>Seus funcionários</h2>
          <hr>
            <% @active_users.each do |company_user|%>   
                <div class="d-flex justify-content-between m-1">         
                    <%= company_user.user.name %> : <%= company_user.user.email %>
                    <%= simple_form_for :company_user,url: company_user_path(company_user), method: :patch do |f| %>
                        <%= f.hidden_field :id, :value => company_user.id %>        
                        <%= f.hidden_field :company_id, :value => @company.id %>
                        <%= f.hidden_field :user_id, :value => company_user.user.id %>
                        <%= f.hidden_field :role, :value => :standard %>
                        <%= f.hidden_field :status, :value => :inactive %>
                        <%= f.submit "Desativar", class: "btn btn-sm btn-danger", data: { confirm: "Tem certeza que deseja desativar esse funcionário? Essa ação não poderá ser cancelada."} %>
                    <% end  %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>